### PR TITLE
Upgrade UxSDK and Fix TwinMaker Query Editor panel hight resize

### PR DESCRIPTION
**Pull request by MO-Elmu**
**What this PR does / why we need it**:
* Upgrade to the latest UxSDK version IotRociUxSDK-JS-Bundled release version 1.0.1537.0
* Fix AWS IoT TwinMaker Query Editor Panel height and resize issue.

**Which issue(s) this PR fixes**:
* Height of the Query Editor panel changes automatically on running a query and also on switching between the tabs (Visual Graph, Query Results and Summary). Resizing is not working as expected and has no value as the panel automatically changes its height.(SIM IOTROCI-9462)

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by iwysiu** [comment]
Hi @MO-Elmu ,

I may be building it incorrectly, but when I tried to build the plugin I got the warning:
```
WARNING in ./panels/query-editor/QueryEditor.tsx 5:45-57
export 'QueryBuilder' (imported as 'QueryBuilder') was not found in 'aws-iot-twinmaker-grafana-utils
```

and when I tried to use the query editor panel, I got this error:
Screen Shot 2023-02-21 at 11 31 07 AM

**Comment by MO-Elmu** [comment]
Hi @iwysiu,
This error tells me you are using the old UxSDK zip (aws-iot-twinmaker-grafana-utils-1.0.0.tgz)in the libs folder. part of this PR I updated this zip file, the old file the exported component was named QueryEditor but in the new version it is named QueryBuilder and this is exactly the same error you are facing.

**Review by iwysiu — APPROVED** [review]
Ah, I had to clear out my dependencies. Approved!

**Comment by MO-Elmu** [comment]
Thanks,

**Pull request merged**
