### PR TITLE
feat(TwinMaker): Setting up sticky video controls

### PR DESCRIPTION
**Pull request by mumanity**
**What this PR does / why we need it**:

- Improves video player user experience.

**Which issue(s) this PR fixes**:

- Applies sticky placement to the `video-upload-request-ui` block.

**Special notes for your reviewer**:

https://user-images.githubusercontent.com/6610619/236571832-afe35cb2-c4df-4e48-a09d-bd18500a5b63.mov

### CODE REVIEW

**Review by TheEvilDev — APPROVED** [review]

**Comment by idastambuk** [comment]
Hi @mumanity, thanks for submitting this!
I looked at the screen recording and I have a question to help me understand the motivation behind the change: 

What is the user experience we're trying to improve? Is it
a. not seeing the "Request video" section when the panel is smaller? However, I notice at some point when resizing the panel, the buttons cover the video controls, which  isn't ideal. 
b. Something else I'm not seeing

It's not a particularly elegant resizing experience to begin with, so there's certainly room for improvement. :) 

An additional thing - When I build the plugin, I'm not having the css applied, probably because the panel-content class doesn't exist anymore as such. 
I would suggest, rather than adding an .scss file and in order to stay consistent, to use the css() method [here](https://github.com/grafana/grafana-iot-twinmaker-app/blob/2e980730d641dcd54eab3cd5e710a4cb03d9b922/src/panels/video-player/styles.ts#L3) to apply the styles targeting just the id inside the wrapper.

**Comment by mumanity** [comment]
> 

Hi [idastambuk](https://github.com/idastambuk), 

The request came from another member of our team to improve the UX by making sure the controls were readily available no matter the video container size. The previous implementation didn't allow viewers to see the `video-upload-request-ui` without having to resize the panel. This change helps ensure easy access to the component at any given size.

**Comment by idastambuk** [comment]
> > 
> 
> Hi [idastambuk](https://github.com/idastambuk),
> 
> The request came from another member of our team to improve the UX by making sure the controls were readily available no matter the video container size. The previous implementation didn't allow viewers to see the `video-upload-request-ui` without having to resize the panel. This change helps ensure easy access to the component at any given size.

Hi @mumanity thanks for the clarification. In that case, you can go ahead and apply the suggested correction and sign the CLA, so we can proceed with the merge

**Comment by mumanity** [comment]
> > > 
> > 
> > 
> > Hi [idastambuk](https://github.com/idastambuk),
> > The request came from another member of our team to improve the UX by making sure the controls were readily available no matter the video container size. The previous implementation didn't allow viewers to see the `video-upload-request-ui` without having to resize the panel. This change helps ensure easy access to the component at any given size.
> 
> Hi @mumanity thanks for the clarification. In that case, you can go ahead and apply the suggested correction and sign the CLA, so we can proceed with the merge

Will do! Thanks for the feedback. :)

**Review by mukeshsahay — APPROVED** [review]

**Comment by iwysiu** [comment]
Hi! It's fine that this was merged, but can @mumanity sign the CLA?

**Comment by mumanity** [comment]
> Hi! It's fine that this was merged, but can @mumanity sign the CLA?

I clicked on the details link yesterday & went through the process. Each time I went back it said I had already signed the CLA. Is there another link that I can reference to confirm? I thought it was odd that after signing it wasn't updating.

**Comment by iwysiu** [comment]
Hmm, once in a while the CLA assistant has problems and gets stuck, I'll take a look. Thanks for telling me!

**Comment by iwysiu** [comment]
I reran it and it didn't pass, but I realized that this commit has a coauthor. Did Emily sign the CLA?

**Comment by mumanity** [comment]
Yes. It looked like it was letting me sign & then not showing approved due to multiple emails setup in my github. We fixed it & shouldn't see any more CLA stuff for my account.

**Pull request merged**
